base.url=YOUR_BASE_URL
base.path=YOUR_BASEPATH
base.env = YOUR_ENV
base.endpoint=YOUR_ENDPOINT

content.type=application/json
accept.type=application/json

response.timeout=2000L
api.key = YOUR_API_KEY
project.id = YOUR_PROJECT_ID

